### ISSUE TITLE
Invalid datetime format error during daylight saving time

### ISSUE THREAD

**Issue by lasselehtinen** [spatie/laravel-health#84] opened 2022-03-30 07:17 UTC
I have been getting the following exception thrown. Perhaps something to do with daylight savings time? The first exception happened at 3:00 and ended at 3:59 at it only happened on March 27th. The timezone is set to UTC in app/config.php.

`Illuminate\Database\QueryException SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2022-03-27 03:59:02' for column 'ended_at' at row 1 (SQL: insert into `health_check_result_history_items` (`check_name`, `check_label`, `status`, `notification_message`, `short_summary`, `meta`, `batch`, `ended_at`, `updated_at`, `created_at`) values (CpuLoad, Cpu Load, ok, , 0 0 0, {"last_minute":0,"last_5_minutes":0,"last_15_minutes":0}, 19f08f33-6db9-40e1-afd9-3db9ab628986, 2022-03-27 03:59:02, 2022-03-27 03:59:02, 2022-03-27 03:59:02)) `

**Comment by freekmurze** [comment] 2022-03-30 07:21
Yeah, I think this is caused by Carbon not taking in account DST. I think it should be fixed at their end. Closing it here.

**Closed by freekmurze** 2022-03-30 07:21 UTC
